[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.108.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = '''
      default-src 'self';
      connect-src 'self' www.netlifystatus.com;
      font-src 'self' cdn.jsdelivr.net fonts.gstatic.com;
      frame-src 'self' www.google.com identity.netlify.com;
      img-src 'self' blob: cdnjs.cloudflare.com data: referrer.disqus.com s.gravatar.com www.gstatic.com;
      manifest-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' identity.netlify.com www.gstatic.com cdn.jsdelivr.net;
      style-src 'self' 'unsafe-inline' cdn.jsdelivr.net fonts.googleapis.com;
      prefetch-src 'self';
      form-action 'none';
      frame-ancestors 'none';
      object-src 'none';
      base-uri 'none';
      upgrade-insecure-requests;'''
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy	= "strict-origin-when-cross-origin"
    Feature-Policy = "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    Cross-Origin-Embedder-Policy-Report-Only = "require-corp; report-to='default'"
    Cross-Origin-Opener-Policy-Report-Only = "same-origin; report-to='default'"
    Cross-Origin-Resource-Policy = "same-site"